# Generated by Django 2.0 on 2017-12-28 12:52

from django.db import migrations, models
import faker.providers.lorem


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='name',
            field=models.CharField(blank=True, default=faker.providers.lorem.Provider.text, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(default=faker.providers.lorem.Provider.text, max_length=300),
        ),
        migrations.AlterField(
            model_name='settingsapp',
            name='page_size',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='authority_to_act',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Authority to Act'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='complete_agreement',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Complete Agreement'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='confidentiality',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Confidentiality'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='contributor_assignment_agreement',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Contributor Assignment Agreement'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='governing_laws',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Governing Laws'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='limited_warranty',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Limited Warranty'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='parties',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Parties'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='payment_terms',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Payment Terms'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='period_of_agreement',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Period of Agreement'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='scope_of_work',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Scope of Work'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='taxes',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Taxes'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='termination',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Termination'),
        ),
        migrations.AlterField(
            model_name='settingscontract',
            name='timing_of_payment',
            field=models.TextField(blank=True, default=faker.providers.lorem.Provider.text, null=True, verbose_name='Timing of Payment'),
        ),
    ]
