# Generated by Django 2.0.1 on 2018-02-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_auto_20180201_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='settingsapp',
            name='icon_color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='color',
            field=models.CharField(blank=True, choices=[('primary', 'Primary'), ('secondary', 'Secondary'), ('success', 'Success'), ('danger', 'Danger'), ('warning', 'Warning'), ('info', 'Info'), ('light', 'Light'), ('dark', 'Dark'), ('muted', 'Muted'), ('white', 'White')], max_length=7, null=True),
        ),
    ]
