# Generated by Django 2.0.1 on 2018-02-03 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0003_auto_20180201_1444'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='note',
            field=models.ManyToManyField(blank=True, limit_choices_to={'active': True}, to='db.Note'),
        ),
    ]
